/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package moe.kkshinkai.yuischeme.app;

import moe.kkshinkai.yuischeme.list.LinkedList;

import static moe.kkshinkai.yuischeme.utilities.StringUtils.join;
import static moe.kkshinkai.yuischeme.utilities.StringUtils.split;
import static moe.kkshinkai.yuischeme.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
